### ISSUE TITLE
Remove namespaces and other PHP >5.3 dependies

### ISSUE THREAD

**Issue by mateuszjarzewski** [mreg-archive/phplibphone#4]
PHP need to be portable, namespaces are not portable, please change it...

**Comment by hanneskod** [comment]
I want to comply with [PSR-4](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md), in which namespaces are non-optional. I also believe in propagating for use of modern php versions. 5.3 was a major improvment for php, and really is not new anymore, bugg and security fixes on the 5.3 branch [stoped a year ago](http://www.phpdeveloper.org/news/19837). All users should upgrade to at least 5.4.

**Comment by mateuszjarzewski** [comment]
It's not as much about php version, as it's about dependencies.

**Comment by hanneskod** [comment]
Could you be more specific? What dependencies are the problem?

**Comment by mateuszjarzewski** [comment]
Namespaces for example. Using them in such a small library is a mistake.

**Comment by hanneskod** [comment]
I think my first reply covers this. Namespaces is a 5.3 feature that should be used.

**Comment by mateuszjarzewski** [comment]
It just make things more complex, so it's worthless epecially in a small, standalone libs like this one.
